<?php
declare(strict_types=1);

return [
    'dashboard' => 'dashboard.php',
    'super/dashboard' => 'modules/dashboards/super.php',
    'hr/dashboard' => 'modules/dashboards/hr.php',
    'production/dashboard' => 'modules/dashboards/production.php',
    'inventory/dashboard' => 'modules/dashboards/inventory.php',
    'dispatch/dashboard' => 'modules/dashboards/dispatch.php',
    'quality/dashboard' => 'modules/dashboards/quality.php',
    'employees/list' => 'modules/employees/index.php',
    'attendance/list' => 'modules/hr/attendance/index.php',
    'leave/list' => 'modules/hr/leave/index.php',
    'payroll/list' => 'modules/hr/payroll/index.php',
    'raw-materials/list' => 'modules/raw_materials/index.php',
    'suppliers/list' => 'modules/suppliers/index.php',
    'production/list' => 'modules/production/index.php',
    'machines/list' => 'modules/machines/index.php',
    'quality/list' => 'modules/quality/index.php',
    'inventory/list' => 'modules/inventory/index.php',
    'dispatch/list' => 'modules/dispatch/index.php',
    'reports/hr' => 'modules/reports/hr.php',
    'reports/production' => 'modules/reports/production.php',
    'reports/inventory' => 'modules/reports/inventory.php',
    'settings/profile' => 'modules/settings/index.php',
    'employee/dashboard' => 'modules/employee/dashboard.php',
    'employee/profile' => 'modules/employee/profile.php',
    'employee/attendance' => 'modules/employee/attendance.php',
    'employee/leave' => 'modules/employee/leave.php',
    'employee/salary' => 'modules/employee/salary.php',
    'employee/change-password' => 'modules/employee/change_password.php',
    'users/index' => 'modules/users/index.php',
    'employees/index' => 'modules/employees/index.php',
    'hr/attendance/index' => 'modules/hr/attendance/index.php',
    'hr/payroll/index' => 'modules/hr/payroll/index.php',
    'hr/leave/index' => 'modules/hr/leave/index.php',
    'hr/employee_records/index' => 'modules/hr/employee_records/index.php',
    'raw_materials/index' => 'modules/raw_materials/index.php',
    'suppliers/index' => 'modules/suppliers/index.php',
    'production/index' => 'modules/production/index.php',
    'machines/index' => 'modules/machines/index.php',
    'quality/index' => 'modules/quality/index.php',
    'inventory/index' => 'modules/inventory/index.php',
    'dispatch/index' => 'modules/dispatch/index.php',
    'reports/index' => 'modules/reports/index.php',
    'settings/index' => 'modules/settings/index.php',
];

